#!/bin/bash -eu

# will write/read MAX_FILE files of COUNT x BLOCK_SIZE Bytes on disks /dev/sdb

MAX_FILE=500
FILE_NAME=disk-test.tmp
BLOCK_SIZE=$((1024*1024*1024))
COUNT=100

function flush {
  # sync unwritten data
  sync
  # drop pagecache/dentries/inodes
  echo 3 > /proc/sys/vm/drop_caches
  # flush buffers of block device
  blockdev --flushbufs $TARGET_DISK
  # flush HDD buffers
  hdparm -q -F $TARGET_DISK &> /dev/null
}

DISKS=`mount | grep '^/dev/sdb' | awk '{ print $1; }'`

for ((itt = 0 ; itt < $MAX_FILE ; itt++)); do
  echo $itt
  for TARGET_DISK in $DISKS do
    MOUNT_POINT=`mount | grep "^$TARGET_DISK " | awk '{ print $3; }' | sed 's#/$##'`
    TARGET_FILE="$MOUNT_POINT/${FILE_NAME}_${itt}"

    echo ---------------------------------------------
    echo Targetting $TARGET_DISK, using $TARGET_FILE
    echo ---------------------------------------------
    rm -f $TARGET_FILE
    echo Flushing caches...
    flush
    echo ----- Write test...
    dd if=/dev/zero of=$TARGET_FILE oflag=direct bs=$BLOCK_SIZE count=$COUNT
    echo Flushing caches...
    flush
    echo ----- Read test...
    dd of=/dev/null if=$TARGET_FILE iflag=direct bs=$BLOCK_SIZE count=$COUNT
    echo Flushing caches...
    flush
    echo ----- Raw read test...
    hdparm -q -t $TARGET_DISK
  done
done

echo
echo Clean up...
for TARGET_DISK in $DISKS; do
  MOUNT_POINT=`mount | grep "^$TARGET_DISK " | awk '{ print $3; }' | sed 's#/$##'`
  TARGET_FILE="$MOUNT_POINT/${FILE_NAME}_*"
  echo rm -f ${TARGET_FILE}
  rm -f ${TARGET_FILE}
done

echo Done.
